### ISSUE TITLE
IntelliJ Ultimate not supported?

### ISSUE THREAD

**Issue by Rikj000** [kagof/intellij-pokemon-progress#3]
I can successfully find and download the plugin in DataGrip.
But not in IntelliJ Ultimate. Also if I manually drop the .zip release in the IntelliJ Ultimate IDE it gives me an unsupported error.

**Comment by kagof** [comment]
Interesting... which version of IntelliJ Ultimate are you on? And what is your OS?

I wrote this plugin in IntelliJ Ultimate, and am currently using it there, so it definitely should work :) I'm currently on version 2020.2.1, so perhaps an issue with an older version of IntelliJ?

**Comment by Rikj000** [comment]
Aha, most likely that will be the issue then. I'm still rolling on v2019.3.2.
I'll try to update, retry and report back during the weekend.

**Comment by kagof** [comment]
Thanks, appreciate the report back!

I thought I wasn't using any features specific to IntelliJ 2020.x, but I've just run the IntelliJ version checker for 2019.3.4 and I see:

![Screenshot 2020-09-18 at 11 19 58](https://user-images.githubusercontent.com/17553493/93586984-13797800-f9a1-11ea-8e86-bc674bbe28cd.png)

I'm guessing this is what you've run into. It looks like if I change this method, I could make this plugin usable on older IntelliJ versions. And moving forward, I wonder if it is worthwhile setting my `build.gradle.kts`'s  `intellij.version` down from `2020.2.1` to `2019.3.2`. I'm assuming that lowers the version of the SDK that the plugin is built with, which should increase the number of people this plugin is available for

**Comment by kagof** [comment]
@Rikj000 I've published version 1.0.1 which should be compatible with IntelliJ 2019.3.x! It is currently being reviewed by JetBrains to be added to the plugin repository, or can be found here <https://github.com/kagof/intellij-pokemon-progress/releases/tag/1.0.1> (`pokemon-progress-1.0.1.zip`) if you want it sooner.

Thanks for pointing this out! Hopefully this plugin should be available to more people now.

**Comment by Rikj000** [comment]
Thank you for the quick response! I'm sad to say that v1.0.1 still throws me the error:   
Plugin 'Pokemon Progress' is incompatible with this installation.   
![Error1](https://user-images.githubusercontent.com/24852597/93590983-02c80280-f99f-11ea-8b61-b92c77f4340f.png)   
![Error2](https://user-images.githubusercontent.com/24852597/93591048-20956780-f99f-11ea-80df-0668f42b734a.png)

**Comment by kagof** [comment]
That's unfortunate...

I was able to install 2019.3.5 and get 1.0.1 working in there, but JetBrains toolbox doesn't seem to let me install 2019.3.2, so I'd have a hard time seeing what's going wrong there.

The error message you're getting also doesn't really give me a whole lot to go on, and at this point it probably isn't really worth me spending a whole lot more time on it, since it (🤞) will be resolved by updating IntelliJ anyways! 

So I guess for now I'd say the solution is to update IntelliJ to at least 2019.3.5 😅

Definitely let me know if it still doesn't work after you update!
